In [2]:
import numpy as np

In [7]:
numpy_array=np.array([1,2,3,4,5])


In [8]:
numpy_array

array([1, 2, 3, 4, 5])

In [9]:
ndm_array=np.array([[1,2,3],
                    [4,5,6],[7,8,9]])

In [10]:
ndm_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
type(ndm_array)

numpy.ndarray

In [4]:
three_dim_array=np.array([[[1,2,3],[4,5,6]],[[5,6,7],[8,9,10]]])

In [6]:
type(three_dim_array)

numpy.ndarray

#np.array()-- Creating multidimenisonal array
##dtype parameter-- which can help us out with deciding the size of the data we are going to store inside our array

In [ ]:
np.array([1,2,3,4,5],dtype=np.int32)
np.array([1,2,3,4,5],dtype=np.int64)
np.array([1,2,3,4,5],dtype=np.float32)
np.array([1,2,3,4,5],dtype=np.bool)


array([1., 2., 3., 4., 5.])

In [ ]:
empty_list =[]
for i in range(16):
    empty_list.append(i)
empty_list
