In [2]:
import numpy as np

In [7]:
numpy_array=np.array([1,2,3,4,5])


In [8]:
numpy_array

array([1, 2, 3, 4, 5])

In [9]:
ndm_array=np.array([[1,2,3],
                    [4,5,6],[7,8,9]])

In [10]:
ndm_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
type(ndm_array)

numpy.ndarray

In [4]:
three_dim_array=np.array([[[1,2,3],[4,5,6]],[[5,6,7],[8,9,10]]])

In [6]:
type(three_dim_array)

numpy.ndarray

#np.array()-- Creating multidimenisonal array
##dtype parameter-- which can help us out with deciding the size of the data we are going to store inside our array

In [8]:
np.array([1,2,3,4,5],dtype=np.int32)
np.array([1,2,3,4,5],dtype=np.int64)
np.array([1,2,3,4,5],dtype=np.float32)
np.array([1,2,3,4,5],dtype=np.bool)


array([1., 2., 3., 4., 5.])

In [9]:
empty_list =[]
for i in range(16):
    empty_list.append(i)
empty_list


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [10]:
#instead of using for loop we can use numpy arange function to create a list of numbers from 0 to 15
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

arange()----> provides the values over a certain range

In [13]:
np.arange(1,15)
np.arange(5,10)
np.arange(2,21,2) #----> 3rd parameter is step size which means it will generate numbers from 2 to 20 with a step size of 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [20]:
arange_data=np.arange(0,16)
arange_data.reshape(4,4)  #----> reshape function is used to change the shape of the array. Here we are changing the shape of the array from (16,) to (4,4) which means we are creating a 2D array with 4 rows and 4 columns.
arange_data.reshape(2,8) #----> reshape function is used to change the shape of the array. Here we are changing the shape of the array from (16,) to (2,8) which means we are creating a 2D array with 2 rows and 8 columns.
arange_data.reshape(8,2) #----> reshape function is used to change the shape of the array. Here we are changing the shape of the array from (16,) to (8,2) which means we are creating a 2D array with 8 rows and 2 columns.
arange_data.reshape(2,4,2) #----> reshape function is used to change the shape of the array. Here we are changing the shape of the array from (16,) to (2,4,2) which means we are creating a 3D array with 2 blocks, 4 rows and 2 columns.

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [21]:
np.ones((4,4))
#ones function is used to create an array of ones. Here we are creating a 2D array of ones with 4 rows and 4 columns.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

zeros()-->#zeros function is used to create an array of zeros. Here we are creating a 2D array of zeros with 4 rows and 5 columns. We can also specify the data type of the array using dtype parameter. Here we are creating an array of zeros with data type int32.

In [23]:
np.zeros((4,5))
np.zeros((4,5),dtype=np.int32) #zeros function is used to create an array of zeros. Here we are creating a 2D array of zeros with 4 rows and 5 columns. We can also specify the data type of the array using dtype parameter. Here we are creating an array of zeros with data type int32.

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

random()-#random function is used to create an array of random numbers between 0 and 1. Here we are creating a 2D array of random numbers with 4 rows and 4 columns. We can also specify the data type of the array using dtype parameter. Here we are creating an array of random numbers with data type float32.

In [24]:
np.random.random((4,4)) #random function is used to create an array of random numbers between 0 and 1. Here we are creating a 2D array of random numbers with 4 rows and 4 columns. We can also specify the data type of the array using dtype parameter. Here we are creating an array of random numbers with data type float32.

array([[0.22785965, 0.33689412, 0.65371249, 0.33399796],
       [0.10833581, 0.9064954 , 0.28260452, 0.29040574],
       [0.4239174 , 0.44193117, 0.48610436, 0.46010038],
       [0.76331623, 0.51571909, 0.11656235, 0.44583803]])

#identity()--->It helps us to create a matrix which are having identical rows and columns

In [25]:
np.identity(3) #identity function is used to create an identity matrix. Here we are creating a 3x3 identity matrix.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#linspace()----> It make sure that every value within the given range going to have similar distance from each other

In [30]:
np.linspace(-10,10,5) #linspace function is used to create an array of evenly spaced numbers between a specified range. Here we are creating an array of 5 evenly spaced numbers between -10 and 10. The 3rd parameter is the number of evenly spaced numbers we want to create.
np.arange(-10,10,5) #arange function is used to create an array of numbers between a specified range with a specified step size. Here we are creating an array of numbers between -10 and 10 with a step size of 5. The 3rd parameter is the step size which means it will generate numbers from -10 to 10 with a step size of 5.

array([-10,  -5,   0,   5,  10])

Important Attributes:
ndim---> stands for n dimensions


In [32]:
arr=np.array([1,2,3,4,5])

In [33]:
arr.ndim #ndim function is used to get the number of dimensions of the array. Here we are getting the number of dimensions of the array which is 1.

1

In [34]:
array_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [35]:
array_3d.ndim

3

In [42]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#Shape attribute provides us with the idea about rows and columns in our dataset or in array

In [41]:
array_array=np.array([[1,2,3],[4,5,6]]) #creating a 2D array with 2 rows and 3 columns.
array_array.shape #shape function is used to get the shape of the array. Here we are getting the shape of the array which is (2,3) which means we have 2 rows and 3 columns in our array.

(2, 3)

Size()----> Provides total number of elements present inside our dataset or array

In [43]:
array= np.array(range(5,25))
size=array.size #size function is used to get the number of elements in the array. Here we are getting the number of elements in the array which is 20.
size

20

#astype() function is used to change the data type of the array. Here we are changing the data type of the array from int32 to float32.
method in pandas is used to explicitly convert (cast) the data type of a pandas object (like a DataFrame or Series) to a specified dtype.

In [49]:
array= np.arange(1,10).reshape(3,3)
array
type(array)
xarrray=array.astype('float32') 

TypeError: Cannot construct a dtype from an array