In [2]:
import numpy as np

The main purpose of NumPy (Numerical Python) is to provide a high-performance way to handle large, multi-dimensional arrays and matrices, along with a massive library of mathematical functions to operate on them.

While Python lists are great for general use, they are incredibly slow for heavy math. NumPy fixes this by bringing the speed of C and Fortran to Python.

In [7]:
numpy_array=np.array([1,2,3,4,5])


In [8]:
numpy_array

array([1, 2, 3, 4, 5])

In [9]:
ndm_array=np.array([[1,2,3],
                    [4,5,6],[7,8,9]])

In [10]:
ndm_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
type(ndm_array)

numpy.ndarray

In [4]:
three_dim_array=np.array([[[1,2,3],[4,5,6]],[[5,6,7],[8,9,10]]])

In [6]:
type(three_dim_array)

numpy.ndarray

#np.array()-- Creating multidimenisonal array
##dtype parameter-- which can help us out with deciding the size of the data we are going to store inside our array

In [8]:
np.array([1,2,3,4,5],dtype=np.int32)
np.array([1,2,3,4,5],dtype=np.int64)
np.array([1,2,3,4,5],dtype=np.float32)
np.array([1,2,3,4,5],dtype=np.bool)


array([1., 2., 3., 4., 5.])

In [9]:
empty_list =[]
for i in range(16):
    empty_list.append(i)
empty_list


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [10]:
#instead of using for loop we can use numpy arange function to create a list of numbers from 0 to 15
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

arange()----> provides the values over a certain range

In [13]:
np.arange(1,15)
np.arange(5,10)
np.arange(2,21,2) #----> 3rd parameter is step size which means it will generate numbers from 2 to 20 with a step size of 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [20]:
arange_data=np.arange(0,16)
arange_data.reshape(4,4)  #----> reshape function is used to change the shape of the array. Here we are changing the shape of the array from (16,) to (4,4) which means we are creating a 2D array with 4 rows and 4 columns.
arange_data.reshape(2,8) #----> reshape function is used to change the shape of the array. Here we are changing the shape of the array from (16,) to (2,8) which means we are creating a 2D array with 2 rows and 8 columns.
arange_data.reshape(8,2) #----> reshape function is used to change the shape of the array. Here we are changing the shape of the array from (16,) to (8,2) which means we are creating a 2D array with 8 rows and 2 columns.
arange_data.reshape(2,4,2) #----> reshape function is used to change the shape of the array. Here we are changing the shape of the array from (16,) to (2,4,2) which means we are creating a 3D array with 2 blocks, 4 rows and 2 columns.

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [21]:
np.ones((4,4))
#ones function is used to create an array of ones. Here we are creating a 2D array of ones with 4 rows and 4 columns.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

zeros()-->#zeros function is used to create an array of zeros. Here we are creating a 2D array of zeros with 4 rows and 5 columns. We can also specify the data type of the array using dtype parameter. Here we are creating an array of zeros with data type int32.

In [23]:
np.zeros((4,5))
np.zeros((4,5),dtype=np.int32) #zeros function is used to create an array of zeros. Here we are creating a 2D array of zeros with 4 rows and 5 columns. We can also specify the data type of the array using dtype parameter. Here we are creating an array of zeros with data type int32.

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

random()-#random function is used to create an array of random numbers between 0 and 1. Here we are creating a 2D array of random numbers with 4 rows and 4 columns. We can also specify the data type of the array using dtype parameter. Here we are creating an array of random numbers with data type float32.

In [24]:
np.random.random((4,4)) #random function is used to create an array of random numbers between 0 and 1. Here we are creating a 2D array of random numbers with 4 rows and 4 columns. We can also specify the data type of the array using dtype parameter. Here we are creating an array of random numbers with data type float32.

array([[0.22785965, 0.33689412, 0.65371249, 0.33399796],
       [0.10833581, 0.9064954 , 0.28260452, 0.29040574],
       [0.4239174 , 0.44193117, 0.48610436, 0.46010038],
       [0.76331623, 0.51571909, 0.11656235, 0.44583803]])

#identity()--->It helps us to create a matrix which are having identical rows and columns

In [25]:
np.identity(3) #identity function is used to create an identity matrix. Here we are creating a 3x3 identity matrix.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#linspace()----> It make sure that every value within the given range going to have similar distance from each other

In [30]:
np.linspace(-10,10,5) #linspace function is used to create an array of evenly spaced numbers between a specified range. Here we are creating an array of 5 evenly spaced numbers between -10 and 10. The 3rd parameter is the number of evenly spaced numbers we want to create.
np.arange(-10,10,5) #arange function is used to create an array of numbers between a specified range with a specified step size. Here we are creating an array of numbers between -10 and 10 with a step size of 5. The 3rd parameter is the step size which means it will generate numbers from -10 to 10 with a step size of 5.

array([-10,  -5,   0,   5,  10])

Important Attributes:
ndim---> stands for n dimensions


In [32]:
arr=np.array([1,2,3,4,5])

In [33]:
arr.ndim #ndim function is used to get the number of dimensions of the array. Here we are getting the number of dimensions of the array which is 1.

1

In [34]:
array_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [35]:
array_3d.ndim

3

In [42]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#Shape attribute provides us with the idea about rows and columns in our dataset or in array

In [41]:
array_array=np.array([[1,2,3],[4,5,6]]) #creating a 2D array with 2 rows and 3 columns.
array_array.shape #shape function is used to get the shape of the array. Here we are getting the shape of the array which is (2,3) which means we have 2 rows and 3 columns in our array.

(2, 3)

Size()----> Provides total number of elements present inside our dataset or array

In [43]:
array= np.array(range(5,25))
size=array.size #size function is used to get the number of elements in the array. Here we are getting the number of elements in the array which is 20.
size

20

#astype() function is used to change the data type of the array. Here we are changing the data type of the array from int32 to float32.
method in pandas is used to explicitly convert (cast) the data type of a pandas object (like a DataFrame or Series) to a specified dtype.

In [ ]:
array= np.arange(1,10).reshape(3,3)
array
type(array)

numpy.ndarray

In [56]:
xarrray=array.astype('float32') 
xarrray.dtype

dtype('float32')

MATHEMATICAL OPERATIONS in numpy
Scalar operations:Scalar operation involves performing a mathematical operation between an array (vector or matrix) and a single number (the scalar).

In [59]:
array=np.random.random((3,3))*100
array

array([[68.28767961, 57.20634911, 48.66844792],
       [25.56869937,  4.73245609, 87.55978968],
       [41.46127447, 91.21138145, 19.73254911]])

In [65]:
array=np.round(array)
array
array=array.astype('int32')
array


array([[68, 57, 49],
       [26,  5, 88],
       [41, 91, 20]], dtype=int32)

#Applying scalar operation to array in terms of mathematical operations


In [67]:
array+2

array([[70, 59, 51],
       [28,  7, 90],
       [43, 93, 22]], dtype=int32)

In [68]:
array-5

array([[63, 52, 44],
       [21,  0, 83],
       [36, 86, 15]], dtype=int32)

In [70]:
array/2

array([[34. , 28.5, 24.5],
       [13. ,  2.5, 44. ],
       [20.5, 45.5, 10. ]])

Vector operations:
While scalar operations involve an array and a single number, vector operations (also called element-wise operations) involve two arrays of the same shape.

In NumPy, when you perform an operation on two vectors, it applies the operation to the corresponding elements at each position. This is the heart of "vectorization"—it allows you to avoid writing for loops in Python, making your code much faster and cleaner.

If you have Vector A= $[a_1, a_2]  
        and Vector B $[b_1, b_2], 
        the operation happens positionally:
        A + B = [a_1 + b_1,  a_2 + b_2]

In [73]:
arr_1= np.arange(1,17).reshape(4,4)
arr_2= np.arange(17,33).reshape(4,4)

In [77]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [78]:
arr_2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [81]:
arr_3=arr_1+arr_2

In [82]:
arr_3>20

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [83]:
arr_1*arr_2

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

Important functions of numpy for machine learning and datascience

max()---> used to calculate max value inside a matrix or array
syntax: np.max(array)

In [84]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [86]:
max_value=np.max(arr_1)
max_value

np.int64(16)

In [87]:
array= np.round(np.random.random((4,4))*100).astype('int32')
array

array([[11, 87, 81,  3],
       [ 4, 87, 96, 63],
       [51, 85, 44, 62],
       [65, 71, 56, 68]], dtype=int32)

axis()---->In NumPy and Pandas, the axis parameter is the "direction" in which an operation is performed.

The Rule of Thumb...

axis=0: Think Vertical (Down the rows)---Column wise operation

axis=1: Think Horizontal (Across the columns) ---Row wise operation

In [88]:
np.max(array,axis=0) #axis=0 means we want to get the maximum value of each column. Here we are getting the maximum value of each column in the array.

array([65, 87, 96, 68], dtype=int32)

In [89]:
np.max(array,axis=1) #axis=1 means we want to get the maximum value of each row. Here we are getting the maximum value of each row in the array.

array([87, 96, 85, 71], dtype=int32)

min()---used for calaculating min value from a matrix or an array
syntax= np.min(array)

In [90]:
np.min(array,axis=0) #axis=0 means we want to get the minimum value of each column. Here we are getting the minimum value of each column in the array.

array([ 4, 71, 44,  3], dtype=int32)

In [91]:
np.min(array,axis=1) #axis=1 means we want to get the minimum value of each row. Here we are getting the minimum value of each row in the array.

array([ 3,  4, 44, 56], dtype=int32)

sum()-----> calculates the sum of all the values of given matrix or array

In [92]:
np.sum(array)

np.int64(934)

In [93]:
np.sum(array,axis=0) #axis=0 means we want to get the sum of each column. Here we are getting the sum of each column in the array.

array([131, 330, 277, 196])

In [94]:
np.sum(array,axis=1) #axis=1 means we want to get the sum of each row. Here we are getting the sum of each row in the array.

array([182, 250, 242, 260])

prod()----It helps in calculating the product of all values inside the matrix

In [95]:
np.prod(array) #prod function is used to get the product of all the elements in the array. Here we are getting the product of all the elements in the array.

np.int64(-5083576007865696256)

In [99]:
array_1d=np.round(np.random.random(10)*10).astype('int32')
array_1d

array([ 3,  9,  0, 10,  0,  6,  3,  8,  6,  4], dtype=int32)

In [100]:
np.prod(array_1d) #prod function is used to get the product of all the elements in the array. Here we are getting the product of all the elements in the array_1d which is a 1D array.

np.int64(0)

In [105]:
np.prod(array,axis=0) #prod function is used to get the product of all the elements in the array. Here we are getting the product of all the elements in each column of the array.

array([  145860, 45678915, 19160064,   796824])

In [106]:
np.prod(array,axis=1) #prod function is used to get the product of all the elements in the array. Here we are getting the product of all the elements in each row of the array.

array([  232551,  2104704, 11825880, 17573920])